name: CI / Test

on:
  push:
    branches:
      - master

jobs:
  ruby/rspec:
    name: CI / Test / Ruby RSpec
    permissions:
      contents: read
      pull-requests: write
    uses: .github/workflows/ci-test.yaml@main
    with:
      framework: ruby/rspec